/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditsIndexRouteImport } from './routes/audits/index'
import { Route as AuditsAssignRouteImport } from './routes/audits/assign'
import { Route as AuditsHistoryRouteImport } from './routes/audits/history'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints/index'
import { Route as ComplaintsAnalyticsRouteImport } from './routes/complaints/analytics'
import { Route as ComplaintsListRouteImport } from './routes/complaints/list'
import { Route as ComplaintsNewRouteImport } from './routes/complaints/new'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as DepartmentsAnalyticsRouteImport } from './routes/departments/analytics'
import { Route as DepartmentsListRouteImport } from './routes/departments/list'
import { Route as DepartmentsNewRouteImport } from './routes/departments/new'
import { Route as EngineerIndexRouteImport } from './routes/engineer/index'
import { Route as EngineerCalendarRouteImport } from './routes/engineer/calendar'
import { Route as EngineerHistoryRouteImport } from './routes/engineer/history'
import { Route as EngineerPerformanceRouteImport } from './routes/engineer/performance'
import { Route as EngineerProfileRouteImport } from './routes/engineer/profile'
import { Route as EngineerSettingsRouteImport } from './routes/engineer/settings'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as EquipmentAnalyticsRouteImport } from './routes/equipment/analytics'
import { Route as EquipmentListRouteImport } from './routes/equipment/list'
import { Route as EquipmentNewRouteImport } from './routes/equipment/new'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventoryAnalyticsRouteImport } from './routes/inventory/analytics'
import { Route as InventoryListRouteImport } from './routes/inventory/list'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance/index'
import { Route as MaintenanceAnalyticsRouteImport } from './routes/maintenance/analytics'
import { Route as MaintenanceListRouteImport } from './routes/maintenance/list'
import { Route as MaintenanceNewRouteImport } from './routes/maintenance/new'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as PurchaseOrdersAnalyticsRouteImport } from './routes/purchase-orders/analytics'
import { Route as PurchaseOrdersListRouteImport } from './routes/purchase-orders/list'
import { Route as PurchaseOrdersNewRouteImport } from './routes/purchase-orders/new'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffDepartmentRouteImport } from './routes/staff/department'
import { Route as StaffNotificationsRouteImport } from './routes/staff/notifications'
import { Route as StaffProfileRouteImport } from './routes/staff/profile'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersAnalyticsRouteImport } from './routes/users/analytics'
import { Route as UsersListRouteImport } from './routes/users/list'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as VendorsAnalyticsRouteImport } from './routes/vendors/analytics'
import { Route as VendorsListRouteImport } from './routes/vendors/list'
import { Route as VendorsNewRouteImport } from './routes/vendors/new'
import { Route as WarrantyIndexRouteImport } from './routes/warranty/index'
import { Route as WarrantyAnalyticsRouteImport } from './routes/warranty/analytics'
import { Route as WarrantyListRouteImport } from './routes/warranty/list'
import { Route as WarrantyNewRouteImport } from './routes/warranty/new'
import { Route as AuditsIdIndexRouteImport } from './routes/audits/$id/index'
import { Route as AuditsIdRespondRouteImport } from './routes/audits/$id/respond'
import { Route as AuditsIdReviewRouteImport } from './routes/audits/$id/review'
import { Route as AuditsTemplatesIndexRouteImport } from './routes/audits/templates/index'
import { Route as AuditsTemplatesIdRouteImport } from './routes/audits/templates/$id'
import { Route as AuditsTemplatesNewRouteImport } from './routes/audits/templates/new'
import { Route as ComplaintsIdIndexRouteImport } from './routes/complaints/$id/index'
import { Route as ComplaintsIdEditRouteImport } from './routes/complaints/$id/edit'
import { Route as ComplaintsIdHistoryRouteImport } from './routes/complaints/$id/history'
import { Route as DepartmentsIdIndexRouteImport } from './routes/departments/$id/index'
import { Route as DepartmentsIdEditRouteImport } from './routes/departments/$id/edit'
import { Route as DepartmentsIdHistoryRouteImport } from './routes/departments/$id/history'
import { Route as EngineerEquipmentIdRouteImport } from './routes/engineer/equipment/$id'
import { Route as EngineerTasksIndexRouteImport } from './routes/engineer/tasks/index'
import { Route as EquipmentIdIndexRouteImport } from './routes/equipment/$id/index'
import { Route as EquipmentIdChecklistRouteImport } from './routes/equipment/$id/checklist'
import { Route as EquipmentIdEditRouteImport } from './routes/equipment/$id/edit'
import { Route as EquipmentIdHistoryRouteImport } from './routes/equipment/$id/history'
import { Route as InventoryIdIndexRouteImport } from './routes/inventory/$id/index'
import { Route as InventoryIdEditRouteImport } from './routes/inventory/$id/edit'
import { Route as InventoryIdHistoryRouteImport } from './routes/inventory/$id/history'
import { Route as MaintenanceIdIndexRouteImport } from './routes/maintenance/$id/index'
import { Route as MaintenanceIdChecklistRouteImport } from './routes/maintenance/$id/checklist'
import { Route as MaintenanceIdCompleteRouteImport } from './routes/maintenance/$id/complete'
import { Route as MaintenanceIdCorrectiveActionRouteImport } from './routes/maintenance/$id/corrective-action'
import { Route as MaintenanceIdEditRouteImport } from './routes/maintenance/$id/edit'
import { Route as MaintenanceIdHistoryRouteImport } from './routes/maintenance/$id/history'
import { Route as MaintenanceIdInvestigationRouteImport } from './routes/maintenance/$id/investigation'
import { Route as MaintenanceIdReportRouteImport } from './routes/maintenance/$id/report'
import { Route as MaintenanceIdRootCauseRouteImport } from './routes/maintenance/$id/root-cause'
import { Route as MaintenanceIdTestingRouteImport } from './routes/maintenance/$id/testing'
import { Route as MaintenanceIdUploadsRouteImport } from './routes/maintenance/$id/uploads'
import { Route as PurchaseOrdersIdIndexRouteImport } from './routes/purchase-orders/$id/index'
import { Route as PurchaseOrdersIdEditRouteImport } from './routes/purchase-orders/$id/edit'
import { Route as PurchaseOrdersIdHistoryRouteImport } from './routes/purchase-orders/$id/history'
import { Route as StaffComplaintsIndexRouteImport } from './routes/staff/complaints/index'
import { Route as StaffComplaintsIdRouteImport } from './routes/staff/complaints/$id'
import { Route as StaffComplaintsNewRouteImport } from './routes/staff/complaints/new'
import { Route as StaffEquipmentIndexRouteImport } from './routes/staff/equipment/index'
import { Route as StaffEquipmentIdRouteImport } from './routes/staff/equipment/$id'
import { Route as StaffMaintenanceIndexRouteImport } from './routes/staff/maintenance/index'
import { Route as StaffMaintenanceIdRouteImport } from './routes/staff/maintenance/$id'
import { Route as StaffReportsIndexRouteImport } from './routes/staff/reports/index'
import { Route as StaffReportsIdRouteImport } from './routes/staff/reports/$id'
import { Route as UsersIdIndexRouteImport } from './routes/users/$id/index'
import { Route as UsersIdEditRouteImport } from './routes/users/$id/edit'
import { Route as UsersIdHistoryRouteImport } from './routes/users/$id/history'
import { Route as VendorsIdIndexRouteImport } from './routes/vendors/$id/index'
import { Route as VendorsIdEditRouteImport } from './routes/vendors/$id/edit'
import { Route as VendorsIdHistoryRouteImport } from './routes/vendors/$id/history'
import { Route as WarrantyIdIndexRouteImport } from './routes/warranty/$id/index'
import { Route as WarrantyIdEditRouteImport } from './routes/warranty/$id/edit'
import { Route as WarrantyIdHistoryRouteImport } from './routes/warranty/$id/history'
import { Route as EngineerTasksIdIndexRouteImport } from './routes/engineer/tasks/$id/index'
import { Route as EngineerTasksIdBreakdownRouteImport } from './routes/engineer/tasks/$id/breakdown'
import { Route as EngineerTasksIdChecklistRouteImport } from './routes/engineer/tasks/$id/checklist'
import { Route as EngineerTasksIdCompleteRouteImport } from './routes/engineer/tasks/$id/complete'
import { Route as EngineerTasksIdReportRouteImport } from './routes/engineer/tasks/$id/report'
import { Route as EngineerTasksIdStartRouteImport } from './routes/engineer/tasks/$id/start'
import { Route as EngineerTasksIdUploadsRouteImport } from './routes/engineer/tasks/$id/uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIndexRoute = AuditsIndexRouteImport.update({
  id: '/audits/',
  path: '/audits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsAssignRoute = AuditsAssignRouteImport.update({
  id: '/audits/assign',
  path: '/audits/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsHistoryRoute = AuditsHistoryRouteImport.update({
  id: '/audits/history',
  path: '/audits/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsAnalyticsRoute = ComplaintsAnalyticsRouteImport.update({
  id: '/complaints/analytics',
  path: '/complaints/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsListRoute = ComplaintsListRouteImport.update({
  id: '/complaints/list',
  path: '/complaints/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsNewRoute = ComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsAnalyticsRoute = DepartmentsAnalyticsRouteImport.update({
  id: '/departments/analytics',
  path: '/departments/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsListRoute = DepartmentsListRouteImport.update({
  id: '/departments/list',
  path: '/departments/list',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsNewRoute = DepartmentsNewRouteImport.update({
  id: '/departments/new',
  path: '/departments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerIndexRoute = EngineerIndexRouteImport.update({
  id: '/engineer/',
  path: '/engineer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerCalendarRoute = EngineerCalendarRouteImport.update({
  id: '/engineer/calendar',
  path: '/engineer/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerHistoryRoute = EngineerHistoryRouteImport.update({
  id: '/engineer/history',
  path: '/engineer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerPerformanceRoute = EngineerPerformanceRouteImport.update({
  id: '/engineer/performance',
  path: '/engineer/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerProfileRoute = EngineerProfileRouteImport.update({
  id: '/engineer/profile',
  path: '/engineer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerSettingsRoute = EngineerSettingsRouteImport.update({
  id: '/engineer/settings',
  path: '/engineer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentAnalyticsRoute = EquipmentAnalyticsRouteImport.update({
  id: '/equipment/analytics',
  path: '/equipment/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentListRoute = EquipmentListRouteImport.update({
  id: '/equipment/list',
  path: '/equipment/list',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentNewRoute = EquipmentNewRouteImport.update({
  id: '/equipment/new',
  path: '/equipment/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAnalyticsRoute = InventoryAnalyticsRouteImport.update({
  id: '/inventory/analytics',
  path: '/inventory/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryListRoute = InventoryListRouteImport.update({
  id: '/inventory/list',
  path: '/inventory/list',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceAnalyticsRoute = MaintenanceAnalyticsRouteImport.update({
  id: '/maintenance/analytics',
  path: '/maintenance/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceListRoute = MaintenanceListRouteImport.update({
  id: '/maintenance/list',
  path: '/maintenance/list',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceNewRoute = MaintenanceNewRouteImport.update({
  id: '/maintenance/new',
  path: '/maintenance/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersAnalyticsRoute = PurchaseOrdersAnalyticsRouteImport.update({
  id: '/purchase-orders/analytics',
  path: '/purchase-orders/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersListRoute = PurchaseOrdersListRouteImport.update({
  id: '/purchase-orders/list',
  path: '/purchase-orders/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersNewRoute = PurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDepartmentRoute = StaffDepartmentRouteImport.update({
  id: '/staff/department',
  path: '/staff/department',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/staff/notifications',
  path: '/staff/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/staff/profile',
  path: '/staff/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAnalyticsRoute = UsersAnalyticsRouteImport.update({
  id: '/users/analytics',
  path: '/users/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersListRoute = UsersListRouteImport.update({
  id: '/users/list',
  path: '/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsAnalyticsRoute = VendorsAnalyticsRouteImport.update({
  id: '/vendors/analytics',
  path: '/vendors/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsListRoute = VendorsListRouteImport.update({
  id: '/vendors/list',
  path: '/vendors/list',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsNewRoute = VendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIndexRoute = WarrantyIndexRouteImport.update({
  id: '/warranty/',
  path: '/warranty/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyAnalyticsRoute = WarrantyAnalyticsRouteImport.update({
  id: '/warranty/analytics',
  path: '/warranty/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyListRoute = WarrantyListRouteImport.update({
  id: '/warranty/list',
  path: '/warranty/list',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyNewRoute = WarrantyNewRouteImport.update({
  id: '/warranty/new',
  path: '/warranty/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdIndexRoute = AuditsIdIndexRouteImport.update({
  id: '/audits/$id/',
  path: '/audits/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdRespondRoute = AuditsIdRespondRouteImport.update({
  id: '/audits/$id/respond',
  path: '/audits/$id/respond',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdReviewRoute = AuditsIdReviewRouteImport.update({
  id: '/audits/$id/review',
  path: '/audits/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsTemplatesIndexRoute = AuditsTemplatesIndexRouteImport.update({
  id: '/audits/templates/',
  path: '/audits/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsTemplatesIdRoute = AuditsTemplatesIdRouteImport.update({
  id: '/audits/templates/$id',
  path: '/audits/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsTemplatesNewRoute = AuditsTemplatesNewRouteImport.update({
  id: '/audits/templates/new',
  path: '/audits/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdIndexRoute = ComplaintsIdIndexRouteImport.update({
  id: '/complaints/$id/',
  path: '/complaints/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdEditRoute = ComplaintsIdEditRouteImport.update({
  id: '/complaints/$id/edit',
  path: '/complaints/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdHistoryRoute = ComplaintsIdHistoryRouteImport.update({
  id: '/complaints/$id/history',
  path: '/complaints/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdIndexRoute = DepartmentsIdIndexRouteImport.update({
  id: '/departments/$id/',
  path: '/departments/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdEditRoute = DepartmentsIdEditRouteImport.update({
  id: '/departments/$id/edit',
  path: '/departments/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdHistoryRoute = DepartmentsIdHistoryRouteImport.update({
  id: '/departments/$id/history',
  path: '/departments/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerEquipmentIdRoute = EngineerEquipmentIdRouteImport.update({
  id: '/engineer/equipment/$id',
  path: '/engineer/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIndexRoute = EngineerTasksIndexRouteImport.update({
  id: '/engineer/tasks/',
  path: '/engineer/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdIndexRoute = EquipmentIdIndexRouteImport.update({
  id: '/equipment/$id/',
  path: '/equipment/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdChecklistRoute = EquipmentIdChecklistRouteImport.update({
  id: '/equipment/$id/checklist',
  path: '/equipment/$id/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdEditRoute = EquipmentIdEditRouteImport.update({
  id: '/equipment/$id/edit',
  path: '/equipment/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdHistoryRoute = EquipmentIdHistoryRouteImport.update({
  id: '/equipment/$id/history',
  path: '/equipment/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdIndexRoute = InventoryIdIndexRouteImport.update({
  id: '/inventory/$id/',
  path: '/inventory/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdEditRoute = InventoryIdEditRouteImport.update({
  id: '/inventory/$id/edit',
  path: '/inventory/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdHistoryRoute = InventoryIdHistoryRouteImport.update({
  id: '/inventory/$id/history',
  path: '/inventory/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdIndexRoute = MaintenanceIdIndexRouteImport.update({
  id: '/maintenance/$id/',
  path: '/maintenance/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdChecklistRoute = MaintenanceIdChecklistRouteImport.update({
  id: '/maintenance/$id/checklist',
  path: '/maintenance/$id/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdCompleteRoute = MaintenanceIdCompleteRouteImport.update({
  id: '/maintenance/$id/complete',
  path: '/maintenance/$id/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdCorrectiveActionRoute =
  MaintenanceIdCorrectiveActionRouteImport.update({
    id: '/maintenance/$id/corrective-action',
    path: '/maintenance/$id/corrective-action',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaintenanceIdEditRoute = MaintenanceIdEditRouteImport.update({
  id: '/maintenance/$id/edit',
  path: '/maintenance/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdHistoryRoute = MaintenanceIdHistoryRouteImport.update({
  id: '/maintenance/$id/history',
  path: '/maintenance/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdInvestigationRoute =
  MaintenanceIdInvestigationRouteImport.update({
    id: '/maintenance/$id/investigation',
    path: '/maintenance/$id/investigation',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaintenanceIdReportRoute = MaintenanceIdReportRouteImport.update({
  id: '/maintenance/$id/report',
  path: '/maintenance/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdRootCauseRoute = MaintenanceIdRootCauseRouteImport.update({
  id: '/maintenance/$id/root-cause',
  path: '/maintenance/$id/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdTestingRoute = MaintenanceIdTestingRouteImport.update({
  id: '/maintenance/$id/testing',
  path: '/maintenance/$id/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIdUploadsRoute = MaintenanceIdUploadsRouteImport.update({
  id: '/maintenance/$id/uploads',
  path: '/maintenance/$id/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdIndexRoute = PurchaseOrdersIdIndexRouteImport.update({
  id: '/purchase-orders/$id/',
  path: '/purchase-orders/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdEditRoute = PurchaseOrdersIdEditRouteImport.update({
  id: '/purchase-orders/$id/edit',
  path: '/purchase-orders/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdHistoryRoute = PurchaseOrdersIdHistoryRouteImport.update({
  id: '/purchase-orders/$id/history',
  path: '/purchase-orders/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffComplaintsIndexRoute = StaffComplaintsIndexRouteImport.update({
  id: '/staff/complaints/',
  path: '/staff/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffComplaintsIdRoute = StaffComplaintsIdRouteImport.update({
  id: '/staff/complaints/$id',
  path: '/staff/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffComplaintsNewRoute = StaffComplaintsNewRouteImport.update({
  id: '/staff/complaints/new',
  path: '/staff/complaints/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEquipmentIndexRoute = StaffEquipmentIndexRouteImport.update({
  id: '/staff/equipment/',
  path: '/staff/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEquipmentIdRoute = StaffEquipmentIdRouteImport.update({
  id: '/staff/equipment/$id',
  path: '/staff/equipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMaintenanceIndexRoute = StaffMaintenanceIndexRouteImport.update({
  id: '/staff/maintenance/',
  path: '/staff/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMaintenanceIdRoute = StaffMaintenanceIdRouteImport.update({
  id: '/staff/maintenance/$id',
  path: '/staff/maintenance/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsIndexRoute = StaffReportsIndexRouteImport.update({
  id: '/staff/reports/',
  path: '/staff/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsIdRoute = StaffReportsIdRouteImport.update({
  id: '/staff/reports/$id',
  path: '/staff/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdIndexRoute = UsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdHistoryRoute = UsersIdHistoryRouteImport.update({
  id: '/users/$id/history',
  path: '/users/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdIndexRoute = VendorsIdIndexRouteImport.update({
  id: '/vendors/$id/',
  path: '/vendors/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdEditRoute = VendorsIdEditRouteImport.update({
  id: '/vendors/$id/edit',
  path: '/vendors/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdHistoryRoute = VendorsIdHistoryRouteImport.update({
  id: '/vendors/$id/history',
  path: '/vendors/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIdIndexRoute = WarrantyIdIndexRouteImport.update({
  id: '/warranty/$id/',
  path: '/warranty/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIdEditRoute = WarrantyIdEditRouteImport.update({
  id: '/warranty/$id/edit',
  path: '/warranty/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyIdHistoryRoute = WarrantyIdHistoryRouteImport.update({
  id: '/warranty/$id/history',
  path: '/warranty/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIdIndexRoute = EngineerTasksIdIndexRouteImport.update({
  id: '/engineer/tasks/$id/',
  path: '/engineer/tasks/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIdBreakdownRoute =
  EngineerTasksIdBreakdownRouteImport.update({
    id: '/engineer/tasks/$id/breakdown',
    path: '/engineer/tasks/$id/breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const EngineerTasksIdChecklistRoute =
  EngineerTasksIdChecklistRouteImport.update({
    id: '/engineer/tasks/$id/checklist',
    path: '/engineer/tasks/$id/checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const EngineerTasksIdCompleteRoute = EngineerTasksIdCompleteRouteImport.update({
  id: '/engineer/tasks/$id/complete',
  path: '/engineer/tasks/$id/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIdReportRoute = EngineerTasksIdReportRouteImport.update({
  id: '/engineer/tasks/$id/report',
  path: '/engineer/tasks/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIdStartRoute = EngineerTasksIdStartRouteImport.update({
  id: '/engineer/tasks/$id/start',
  path: '/engineer/tasks/$id/start',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTasksIdUploadsRoute = EngineerTasksIdUploadsRouteImport.update({
  id: '/engineer/tasks/$id/uploads',
  path: '/engineer/tasks/$id/uploads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/audits/assign': typeof AuditsAssignRoute
  '/audits/history': typeof AuditsHistoryRoute
  '/complaints/analytics': typeof ComplaintsAnalyticsRoute
  '/complaints/list': typeof ComplaintsListRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/departments/analytics': typeof DepartmentsAnalyticsRoute
  '/departments/list': typeof DepartmentsListRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/engineer/calendar': typeof EngineerCalendarRoute
  '/engineer/history': typeof EngineerHistoryRoute
  '/engineer/performance': typeof EngineerPerformanceRoute
  '/engineer/profile': typeof EngineerProfileRoute
  '/engineer/settings': typeof EngineerSettingsRoute
  '/equipment/analytics': typeof EquipmentAnalyticsRoute
  '/equipment/list': typeof EquipmentListRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/analytics': typeof InventoryAnalyticsRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/maintenance/analytics': typeof MaintenanceAnalyticsRoute
  '/maintenance/list': typeof MaintenanceListRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/purchase-orders/analytics': typeof PurchaseOrdersAnalyticsRoute
  '/purchase-orders/list': typeof PurchaseOrdersListRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/staff/department': typeof StaffDepartmentRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/users/analytics': typeof UsersAnalyticsRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/analytics': typeof VendorsAnalyticsRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/new': typeof VendorsNewRoute
  '/warranty/analytics': typeof WarrantyAnalyticsRoute
  '/warranty/list': typeof WarrantyListRoute
  '/warranty/new': typeof WarrantyNewRoute
  '/audits/': typeof AuditsIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/engineer/': typeof EngineerIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/audits/$id/respond': typeof AuditsIdRespondRoute
  '/audits/$id/review': typeof AuditsIdReviewRoute
  '/audits/templates/$id': typeof AuditsTemplatesIdRoute
  '/audits/templates/new': typeof AuditsTemplatesNewRoute
  '/complaints/$id/edit': typeof ComplaintsIdEditRoute
  '/complaints/$id/history': typeof ComplaintsIdHistoryRoute
  '/departments/$id/edit': typeof DepartmentsIdEditRoute
  '/departments/$id/history': typeof DepartmentsIdHistoryRoute
  '/engineer/equipment/$id': typeof EngineerEquipmentIdRoute
  '/equipment/$id/checklist': typeof EquipmentIdChecklistRoute
  '/equipment/$id/edit': typeof EquipmentIdEditRoute
  '/equipment/$id/history': typeof EquipmentIdHistoryRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/inventory/$id/history': typeof InventoryIdHistoryRoute
  '/maintenance/$id/checklist': typeof MaintenanceIdChecklistRoute
  '/maintenance/$id/complete': typeof MaintenanceIdCompleteRoute
  '/maintenance/$id/corrective-action': typeof MaintenanceIdCorrectiveActionRoute
  '/maintenance/$id/edit': typeof MaintenanceIdEditRoute
  '/maintenance/$id/history': typeof MaintenanceIdHistoryRoute
  '/maintenance/$id/investigation': typeof MaintenanceIdInvestigationRoute
  '/maintenance/$id/report': typeof MaintenanceIdReportRoute
  '/maintenance/$id/root-cause': typeof MaintenanceIdRootCauseRoute
  '/maintenance/$id/testing': typeof MaintenanceIdTestingRoute
  '/maintenance/$id/uploads': typeof MaintenanceIdUploadsRoute
  '/purchase-orders/$id/edit': typeof PurchaseOrdersIdEditRoute
  '/purchase-orders/$id/history': typeof PurchaseOrdersIdHistoryRoute
  '/staff/complaints/$id': typeof StaffComplaintsIdRoute
  '/staff/complaints/new': typeof StaffComplaintsNewRoute
  '/staff/equipment/$id': typeof StaffEquipmentIdRoute
  '/staff/maintenance/$id': typeof StaffMaintenanceIdRoute
  '/staff/reports/$id': typeof StaffReportsIdRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/users/$id/history': typeof UsersIdHistoryRoute
  '/vendors/$id/edit': typeof VendorsIdEditRoute
  '/vendors/$id/history': typeof VendorsIdHistoryRoute
  '/warranty/$id/edit': typeof WarrantyIdEditRoute
  '/warranty/$id/history': typeof WarrantyIdHistoryRoute
  '/audits/$id/': typeof AuditsIdIndexRoute
  '/audits/templates/': typeof AuditsTemplatesIndexRoute
  '/complaints/$id/': typeof ComplaintsIdIndexRoute
  '/departments/$id/': typeof DepartmentsIdIndexRoute
  '/engineer/tasks/': typeof EngineerTasksIndexRoute
  '/equipment/$id/': typeof EquipmentIdIndexRoute
  '/inventory/$id/': typeof InventoryIdIndexRoute
  '/maintenance/$id/': typeof MaintenanceIdIndexRoute
  '/purchase-orders/$id/': typeof PurchaseOrdersIdIndexRoute
  '/staff/complaints/': typeof StaffComplaintsIndexRoute
  '/staff/equipment/': typeof StaffEquipmentIndexRoute
  '/staff/maintenance/': typeof StaffMaintenanceIndexRoute
  '/staff/reports/': typeof StaffReportsIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
  '/vendors/$id/': typeof VendorsIdIndexRoute
  '/warranty/$id/': typeof WarrantyIdIndexRoute
  '/engineer/tasks/$id/breakdown': typeof EngineerTasksIdBreakdownRoute
  '/engineer/tasks/$id/checklist': typeof EngineerTasksIdChecklistRoute
  '/engineer/tasks/$id/complete': typeof EngineerTasksIdCompleteRoute
  '/engineer/tasks/$id/report': typeof EngineerTasksIdReportRoute
  '/engineer/tasks/$id/start': typeof EngineerTasksIdStartRoute
  '/engineer/tasks/$id/uploads': typeof EngineerTasksIdUploadsRoute
  '/engineer/tasks/$id/': typeof EngineerTasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/audits/assign': typeof AuditsAssignRoute
  '/audits/history': typeof AuditsHistoryRoute
  '/complaints/analytics': typeof ComplaintsAnalyticsRoute
  '/complaints/list': typeof ComplaintsListRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/departments/analytics': typeof DepartmentsAnalyticsRoute
  '/departments/list': typeof DepartmentsListRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/engineer/calendar': typeof EngineerCalendarRoute
  '/engineer/history': typeof EngineerHistoryRoute
  '/engineer/performance': typeof EngineerPerformanceRoute
  '/engineer/profile': typeof EngineerProfileRoute
  '/engineer/settings': typeof EngineerSettingsRoute
  '/equipment/analytics': typeof EquipmentAnalyticsRoute
  '/equipment/list': typeof EquipmentListRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/analytics': typeof InventoryAnalyticsRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/maintenance/analytics': typeof MaintenanceAnalyticsRoute
  '/maintenance/list': typeof MaintenanceListRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/purchase-orders/analytics': typeof PurchaseOrdersAnalyticsRoute
  '/purchase-orders/list': typeof PurchaseOrdersListRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/staff/department': typeof StaffDepartmentRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/users/analytics': typeof UsersAnalyticsRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/analytics': typeof VendorsAnalyticsRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/new': typeof VendorsNewRoute
  '/warranty/analytics': typeof WarrantyAnalyticsRoute
  '/warranty/list': typeof WarrantyListRoute
  '/warranty/new': typeof WarrantyNewRoute
  '/audits': typeof AuditsIndexRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/engineer': typeof EngineerIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/staff': typeof StaffIndexRoute
  '/users': typeof UsersIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/warranty': typeof WarrantyIndexRoute
  '/audits/$id/respond': typeof AuditsIdRespondRoute
  '/audits/$id/review': typeof AuditsIdReviewRoute
  '/audits/templates/$id': typeof AuditsTemplatesIdRoute
  '/audits/templates/new': typeof AuditsTemplatesNewRoute
  '/complaints/$id/edit': typeof ComplaintsIdEditRoute
  '/complaints/$id/history': typeof ComplaintsIdHistoryRoute
  '/departments/$id/edit': typeof DepartmentsIdEditRoute
  '/departments/$id/history': typeof DepartmentsIdHistoryRoute
  '/engineer/equipment/$id': typeof EngineerEquipmentIdRoute
  '/equipment/$id/checklist': typeof EquipmentIdChecklistRoute
  '/equipment/$id/edit': typeof EquipmentIdEditRoute
  '/equipment/$id/history': typeof EquipmentIdHistoryRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/inventory/$id/history': typeof InventoryIdHistoryRoute
  '/maintenance/$id/checklist': typeof MaintenanceIdChecklistRoute
  '/maintenance/$id/complete': typeof MaintenanceIdCompleteRoute
  '/maintenance/$id/corrective-action': typeof MaintenanceIdCorrectiveActionRoute
  '/maintenance/$id/edit': typeof MaintenanceIdEditRoute
  '/maintenance/$id/history': typeof MaintenanceIdHistoryRoute
  '/maintenance/$id/investigation': typeof MaintenanceIdInvestigationRoute
  '/maintenance/$id/report': typeof MaintenanceIdReportRoute
  '/maintenance/$id/root-cause': typeof MaintenanceIdRootCauseRoute
  '/maintenance/$id/testing': typeof MaintenanceIdTestingRoute
  '/maintenance/$id/uploads': typeof MaintenanceIdUploadsRoute
  '/purchase-orders/$id/edit': typeof PurchaseOrdersIdEditRoute
  '/purchase-orders/$id/history': typeof PurchaseOrdersIdHistoryRoute
  '/staff/complaints/$id': typeof StaffComplaintsIdRoute
  '/staff/complaints/new': typeof StaffComplaintsNewRoute
  '/staff/equipment/$id': typeof StaffEquipmentIdRoute
  '/staff/maintenance/$id': typeof StaffMaintenanceIdRoute
  '/staff/reports/$id': typeof StaffReportsIdRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/users/$id/history': typeof UsersIdHistoryRoute
  '/vendors/$id/edit': typeof VendorsIdEditRoute
  '/vendors/$id/history': typeof VendorsIdHistoryRoute
  '/warranty/$id/edit': typeof WarrantyIdEditRoute
  '/warranty/$id/history': typeof WarrantyIdHistoryRoute
  '/audits/$id': typeof AuditsIdIndexRoute
  '/audits/templates': typeof AuditsTemplatesIndexRoute
  '/complaints/$id': typeof ComplaintsIdIndexRoute
  '/departments/$id': typeof DepartmentsIdIndexRoute
  '/engineer/tasks': typeof EngineerTasksIndexRoute
  '/equipment/$id': typeof EquipmentIdIndexRoute
  '/inventory/$id': typeof InventoryIdIndexRoute
  '/maintenance/$id': typeof MaintenanceIdIndexRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdIndexRoute
  '/staff/complaints': typeof StaffComplaintsIndexRoute
  '/staff/equipment': typeof StaffEquipmentIndexRoute
  '/staff/maintenance': typeof StaffMaintenanceIndexRoute
  '/staff/reports': typeof StaffReportsIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
  '/vendors/$id': typeof VendorsIdIndexRoute
  '/warranty/$id': typeof WarrantyIdIndexRoute
  '/engineer/tasks/$id/breakdown': typeof EngineerTasksIdBreakdownRoute
  '/engineer/tasks/$id/checklist': typeof EngineerTasksIdChecklistRoute
  '/engineer/tasks/$id/complete': typeof EngineerTasksIdCompleteRoute
  '/engineer/tasks/$id/report': typeof EngineerTasksIdReportRoute
  '/engineer/tasks/$id/start': typeof EngineerTasksIdStartRoute
  '/engineer/tasks/$id/uploads': typeof EngineerTasksIdUploadsRoute
  '/engineer/tasks/$id': typeof EngineerTasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/audits/assign': typeof AuditsAssignRoute
  '/audits/history': typeof AuditsHistoryRoute
  '/complaints/analytics': typeof ComplaintsAnalyticsRoute
  '/complaints/list': typeof ComplaintsListRoute
  '/complaints/new': typeof ComplaintsNewRoute
  '/departments/analytics': typeof DepartmentsAnalyticsRoute
  '/departments/list': typeof DepartmentsListRoute
  '/departments/new': typeof DepartmentsNewRoute
  '/engineer/calendar': typeof EngineerCalendarRoute
  '/engineer/history': typeof EngineerHistoryRoute
  '/engineer/performance': typeof EngineerPerformanceRoute
  '/engineer/profile': typeof EngineerProfileRoute
  '/engineer/settings': typeof EngineerSettingsRoute
  '/equipment/analytics': typeof EquipmentAnalyticsRoute
  '/equipment/list': typeof EquipmentListRoute
  '/equipment/new': typeof EquipmentNewRoute
  '/inventory/analytics': typeof InventoryAnalyticsRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/maintenance/analytics': typeof MaintenanceAnalyticsRoute
  '/maintenance/list': typeof MaintenanceListRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/purchase-orders/analytics': typeof PurchaseOrdersAnalyticsRoute
  '/purchase-orders/list': typeof PurchaseOrdersListRoute
  '/purchase-orders/new': typeof PurchaseOrdersNewRoute
  '/staff/department': typeof StaffDepartmentRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/users/analytics': typeof UsersAnalyticsRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/vendors/analytics': typeof VendorsAnalyticsRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/new': typeof VendorsNewRoute
  '/warranty/analytics': typeof WarrantyAnalyticsRoute
  '/warranty/list': typeof WarrantyListRoute
  '/warranty/new': typeof WarrantyNewRoute
  '/audits/': typeof AuditsIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/engineer/': typeof EngineerIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/warranty/': typeof WarrantyIndexRoute
  '/audits/$id/respond': typeof AuditsIdRespondRoute
  '/audits/$id/review': typeof AuditsIdReviewRoute
  '/audits/templates/$id': typeof AuditsTemplatesIdRoute
  '/audits/templates/new': typeof AuditsTemplatesNewRoute
  '/complaints/$id/edit': typeof ComplaintsIdEditRoute
  '/complaints/$id/history': typeof ComplaintsIdHistoryRoute
  '/departments/$id/edit': typeof DepartmentsIdEditRoute
  '/departments/$id/history': typeof DepartmentsIdHistoryRoute
  '/engineer/equipment/$id': typeof EngineerEquipmentIdRoute
  '/equipment/$id/checklist': typeof EquipmentIdChecklistRoute
  '/equipment/$id/edit': typeof EquipmentIdEditRoute
  '/equipment/$id/history': typeof EquipmentIdHistoryRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/inventory/$id/history': typeof InventoryIdHistoryRoute
  '/maintenance/$id/checklist': typeof MaintenanceIdChecklistRoute
  '/maintenance/$id/complete': typeof MaintenanceIdCompleteRoute
  '/maintenance/$id/corrective-action': typeof MaintenanceIdCorrectiveActionRoute
  '/maintenance/$id/edit': typeof MaintenanceIdEditRoute
  '/maintenance/$id/history': typeof MaintenanceIdHistoryRoute
  '/maintenance/$id/investigation': typeof MaintenanceIdInvestigationRoute
  '/maintenance/$id/report': typeof MaintenanceIdReportRoute
  '/maintenance/$id/root-cause': typeof MaintenanceIdRootCauseRoute
  '/maintenance/$id/testing': typeof MaintenanceIdTestingRoute
  '/maintenance/$id/uploads': typeof MaintenanceIdUploadsRoute
  '/purchase-orders/$id/edit': typeof PurchaseOrdersIdEditRoute
  '/purchase-orders/$id/history': typeof PurchaseOrdersIdHistoryRoute
  '/staff/complaints/$id': typeof StaffComplaintsIdRoute
  '/staff/complaints/new': typeof StaffComplaintsNewRoute
  '/staff/equipment/$id': typeof StaffEquipmentIdRoute
  '/staff/maintenance/$id': typeof StaffMaintenanceIdRoute
  '/staff/reports/$id': typeof StaffReportsIdRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/users/$id/history': typeof UsersIdHistoryRoute
  '/vendors/$id/edit': typeof VendorsIdEditRoute
  '/vendors/$id/history': typeof VendorsIdHistoryRoute
  '/warranty/$id/edit': typeof WarrantyIdEditRoute
  '/warranty/$id/history': typeof WarrantyIdHistoryRoute
  '/audits/$id/': typeof AuditsIdIndexRoute
  '/audits/templates/': typeof AuditsTemplatesIndexRoute
  '/complaints/$id/': typeof ComplaintsIdIndexRoute
  '/departments/$id/': typeof DepartmentsIdIndexRoute
  '/engineer/tasks/': typeof EngineerTasksIndexRoute
  '/equipment/$id/': typeof EquipmentIdIndexRoute
  '/inventory/$id/': typeof InventoryIdIndexRoute
  '/maintenance/$id/': typeof MaintenanceIdIndexRoute
  '/purchase-orders/$id/': typeof PurchaseOrdersIdIndexRoute
  '/staff/complaints/': typeof StaffComplaintsIndexRoute
  '/staff/equipment/': typeof StaffEquipmentIndexRoute
  '/staff/maintenance/': typeof StaffMaintenanceIndexRoute
  '/staff/reports/': typeof StaffReportsIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
  '/vendors/$id/': typeof VendorsIdIndexRoute
  '/warranty/$id/': typeof WarrantyIdIndexRoute
  '/engineer/tasks/$id/breakdown': typeof EngineerTasksIdBreakdownRoute
  '/engineer/tasks/$id/checklist': typeof EngineerTasksIdChecklistRoute
  '/engineer/tasks/$id/complete': typeof EngineerTasksIdCompleteRoute
  '/engineer/tasks/$id/report': typeof EngineerTasksIdReportRoute
  '/engineer/tasks/$id/start': typeof EngineerTasksIdStartRoute
  '/engineer/tasks/$id/uploads': typeof EngineerTasksIdUploadsRoute
  '/engineer/tasks/$id/': typeof EngineerTasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/audits/assign'
    | '/audits/history'
    | '/complaints/analytics'
    | '/complaints/list'
    | '/complaints/new'
    | '/departments/analytics'
    | '/departments/list'
    | '/departments/new'
    | '/engineer/calendar'
    | '/engineer/history'
    | '/engineer/performance'
    | '/engineer/profile'
    | '/engineer/settings'
    | '/equipment/analytics'
    | '/equipment/list'
    | '/equipment/new'
    | '/inventory/analytics'
    | '/inventory/list'
    | '/inventory/new'
    | '/maintenance/analytics'
    | '/maintenance/list'
    | '/maintenance/new'
    | '/purchase-orders/analytics'
    | '/purchase-orders/list'
    | '/purchase-orders/new'
    | '/staff/department'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/settings'
    | '/users/analytics'
    | '/users/list'
    | '/users/new'
    | '/vendors/analytics'
    | '/vendors/list'
    | '/vendors/new'
    | '/warranty/analytics'
    | '/warranty/list'
    | '/warranty/new'
    | '/audits/'
    | '/complaints/'
    | '/departments/'
    | '/engineer/'
    | '/equipment/'
    | '/inventory/'
    | '/maintenance/'
    | '/purchase-orders/'
    | '/staff/'
    | '/users/'
    | '/vendors/'
    | '/warranty/'
    | '/audits/$id/respond'
    | '/audits/$id/review'
    | '/audits/templates/$id'
    | '/audits/templates/new'
    | '/complaints/$id/edit'
    | '/complaints/$id/history'
    | '/departments/$id/edit'
    | '/departments/$id/history'
    | '/engineer/equipment/$id'
    | '/equipment/$id/checklist'
    | '/equipment/$id/edit'
    | '/equipment/$id/history'
    | '/inventory/$id/edit'
    | '/inventory/$id/history'
    | '/maintenance/$id/checklist'
    | '/maintenance/$id/complete'
    | '/maintenance/$id/corrective-action'
    | '/maintenance/$id/edit'
    | '/maintenance/$id/history'
    | '/maintenance/$id/investigation'
    | '/maintenance/$id/report'
    | '/maintenance/$id/root-cause'
    | '/maintenance/$id/testing'
    | '/maintenance/$id/uploads'
    | '/purchase-orders/$id/edit'
    | '/purchase-orders/$id/history'
    | '/staff/complaints/$id'
    | '/staff/complaints/new'
    | '/staff/equipment/$id'
    | '/staff/maintenance/$id'
    | '/staff/reports/$id'
    | '/users/$id/edit'
    | '/users/$id/history'
    | '/vendors/$id/edit'
    | '/vendors/$id/history'
    | '/warranty/$id/edit'
    | '/warranty/$id/history'
    | '/audits/$id/'
    | '/audits/templates/'
    | '/complaints/$id/'
    | '/departments/$id/'
    | '/engineer/tasks/'
    | '/equipment/$id/'
    | '/inventory/$id/'
    | '/maintenance/$id/'
    | '/purchase-orders/$id/'
    | '/staff/complaints/'
    | '/staff/equipment/'
    | '/staff/maintenance/'
    | '/staff/reports/'
    | '/users/$id/'
    | '/vendors/$id/'
    | '/warranty/$id/'
    | '/engineer/tasks/$id/breakdown'
    | '/engineer/tasks/$id/checklist'
    | '/engineer/tasks/$id/complete'
    | '/engineer/tasks/$id/report'
    | '/engineer/tasks/$id/start'
    | '/engineer/tasks/$id/uploads'
    | '/engineer/tasks/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/audits/assign'
    | '/audits/history'
    | '/complaints/analytics'
    | '/complaints/list'
    | '/complaints/new'
    | '/departments/analytics'
    | '/departments/list'
    | '/departments/new'
    | '/engineer/calendar'
    | '/engineer/history'
    | '/engineer/performance'
    | '/engineer/profile'
    | '/engineer/settings'
    | '/equipment/analytics'
    | '/equipment/list'
    | '/equipment/new'
    | '/inventory/analytics'
    | '/inventory/list'
    | '/inventory/new'
    | '/maintenance/analytics'
    | '/maintenance/list'
    | '/maintenance/new'
    | '/purchase-orders/analytics'
    | '/purchase-orders/list'
    | '/purchase-orders/new'
    | '/staff/department'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/settings'
    | '/users/analytics'
    | '/users/list'
    | '/users/new'
    | '/vendors/analytics'
    | '/vendors/list'
    | '/vendors/new'
    | '/warranty/analytics'
    | '/warranty/list'
    | '/warranty/new'
    | '/audits'
    | '/complaints'
    | '/departments'
    | '/engineer'
    | '/equipment'
    | '/inventory'
    | '/maintenance'
    | '/purchase-orders'
    | '/staff'
    | '/users'
    | '/vendors'
    | '/warranty'
    | '/audits/$id/respond'
    | '/audits/$id/review'
    | '/audits/templates/$id'
    | '/audits/templates/new'
    | '/complaints/$id/edit'
    | '/complaints/$id/history'
    | '/departments/$id/edit'
    | '/departments/$id/history'
    | '/engineer/equipment/$id'
    | '/equipment/$id/checklist'
    | '/equipment/$id/edit'
    | '/equipment/$id/history'
    | '/inventory/$id/edit'
    | '/inventory/$id/history'
    | '/maintenance/$id/checklist'
    | '/maintenance/$id/complete'
    | '/maintenance/$id/corrective-action'
    | '/maintenance/$id/edit'
    | '/maintenance/$id/history'
    | '/maintenance/$id/investigation'
    | '/maintenance/$id/report'
    | '/maintenance/$id/root-cause'
    | '/maintenance/$id/testing'
    | '/maintenance/$id/uploads'
    | '/purchase-orders/$id/edit'
    | '/purchase-orders/$id/history'
    | '/staff/complaints/$id'
    | '/staff/complaints/new'
    | '/staff/equipment/$id'
    | '/staff/maintenance/$id'
    | '/staff/reports/$id'
    | '/users/$id/edit'
    | '/users/$id/history'
    | '/vendors/$id/edit'
    | '/vendors/$id/history'
    | '/warranty/$id/edit'
    | '/warranty/$id/history'
    | '/audits/$id'
    | '/audits/templates'
    | '/complaints/$id'
    | '/departments/$id'
    | '/engineer/tasks'
    | '/equipment/$id'
    | '/inventory/$id'
    | '/maintenance/$id'
    | '/purchase-orders/$id'
    | '/staff/complaints'
    | '/staff/equipment'
    | '/staff/maintenance'
    | '/staff/reports'
    | '/users/$id'
    | '/vendors/$id'
    | '/warranty/$id'
    | '/engineer/tasks/$id/breakdown'
    | '/engineer/tasks/$id/checklist'
    | '/engineer/tasks/$id/complete'
    | '/engineer/tasks/$id/report'
    | '/engineer/tasks/$id/start'
    | '/engineer/tasks/$id/uploads'
    | '/engineer/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/audits/assign'
    | '/audits/history'
    | '/complaints/analytics'
    | '/complaints/list'
    | '/complaints/new'
    | '/departments/analytics'
    | '/departments/list'
    | '/departments/new'
    | '/engineer/calendar'
    | '/engineer/history'
    | '/engineer/performance'
    | '/engineer/profile'
    | '/engineer/settings'
    | '/equipment/analytics'
    | '/equipment/list'
    | '/equipment/new'
    | '/inventory/analytics'
    | '/inventory/list'
    | '/inventory/new'
    | '/maintenance/analytics'
    | '/maintenance/list'
    | '/maintenance/new'
    | '/purchase-orders/analytics'
    | '/purchase-orders/list'
    | '/purchase-orders/new'
    | '/staff/department'
    | '/staff/notifications'
    | '/staff/profile'
    | '/staff/settings'
    | '/users/analytics'
    | '/users/list'
    | '/users/new'
    | '/vendors/analytics'
    | '/vendors/list'
    | '/vendors/new'
    | '/warranty/analytics'
    | '/warranty/list'
    | '/warranty/new'
    | '/audits/'
    | '/complaints/'
    | '/departments/'
    | '/engineer/'
    | '/equipment/'
    | '/inventory/'
    | '/maintenance/'
    | '/purchase-orders/'
    | '/staff/'
    | '/users/'
    | '/vendors/'
    | '/warranty/'
    | '/audits/$id/respond'
    | '/audits/$id/review'
    | '/audits/templates/$id'
    | '/audits/templates/new'
    | '/complaints/$id/edit'
    | '/complaints/$id/history'
    | '/departments/$id/edit'
    | '/departments/$id/history'
    | '/engineer/equipment/$id'
    | '/equipment/$id/checklist'
    | '/equipment/$id/edit'
    | '/equipment/$id/history'
    | '/inventory/$id/edit'
    | '/inventory/$id/history'
    | '/maintenance/$id/checklist'
    | '/maintenance/$id/complete'
    | '/maintenance/$id/corrective-action'
    | '/maintenance/$id/edit'
    | '/maintenance/$id/history'
    | '/maintenance/$id/investigation'
    | '/maintenance/$id/report'
    | '/maintenance/$id/root-cause'
    | '/maintenance/$id/testing'
    | '/maintenance/$id/uploads'
    | '/purchase-orders/$id/edit'
    | '/purchase-orders/$id/history'
    | '/staff/complaints/$id'
    | '/staff/complaints/new'
    | '/staff/equipment/$id'
    | '/staff/maintenance/$id'
    | '/staff/reports/$id'
    | '/users/$id/edit'
    | '/users/$id/history'
    | '/vendors/$id/edit'
    | '/vendors/$id/history'
    | '/warranty/$id/edit'
    | '/warranty/$id/history'
    | '/audits/$id/'
    | '/audits/templates/'
    | '/complaints/$id/'
    | '/departments/$id/'
    | '/engineer/tasks/'
    | '/equipment/$id/'
    | '/inventory/$id/'
    | '/maintenance/$id/'
    | '/purchase-orders/$id/'
    | '/staff/complaints/'
    | '/staff/equipment/'
    | '/staff/maintenance/'
    | '/staff/reports/'
    | '/users/$id/'
    | '/vendors/$id/'
    | '/warranty/$id/'
    | '/engineer/tasks/$id/breakdown'
    | '/engineer/tasks/$id/checklist'
    | '/engineer/tasks/$id/complete'
    | '/engineer/tasks/$id/report'
    | '/engineer/tasks/$id/start'
    | '/engineer/tasks/$id/uploads'
    | '/engineer/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  AuditsAssignRoute: typeof AuditsAssignRoute
  AuditsHistoryRoute: typeof AuditsHistoryRoute
  ComplaintsAnalyticsRoute: typeof ComplaintsAnalyticsRoute
  ComplaintsListRoute: typeof ComplaintsListRoute
  ComplaintsNewRoute: typeof ComplaintsNewRoute
  DepartmentsAnalyticsRoute: typeof DepartmentsAnalyticsRoute
  DepartmentsListRoute: typeof DepartmentsListRoute
  DepartmentsNewRoute: typeof DepartmentsNewRoute
  EngineerCalendarRoute: typeof EngineerCalendarRoute
  EngineerHistoryRoute: typeof EngineerHistoryRoute
  EngineerPerformanceRoute: typeof EngineerPerformanceRoute
  EngineerProfileRoute: typeof EngineerProfileRoute
  EngineerSettingsRoute: typeof EngineerSettingsRoute
  EquipmentAnalyticsRoute: typeof EquipmentAnalyticsRoute
  EquipmentListRoute: typeof EquipmentListRoute
  EquipmentNewRoute: typeof EquipmentNewRoute
  InventoryAnalyticsRoute: typeof InventoryAnalyticsRoute
  InventoryListRoute: typeof InventoryListRoute
  InventoryNewRoute: typeof InventoryNewRoute
  MaintenanceAnalyticsRoute: typeof MaintenanceAnalyticsRoute
  MaintenanceListRoute: typeof MaintenanceListRoute
  MaintenanceNewRoute: typeof MaintenanceNewRoute
  PurchaseOrdersAnalyticsRoute: typeof PurchaseOrdersAnalyticsRoute
  PurchaseOrdersListRoute: typeof PurchaseOrdersListRoute
  PurchaseOrdersNewRoute: typeof PurchaseOrdersNewRoute
  StaffDepartmentRoute: typeof StaffDepartmentRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  UsersAnalyticsRoute: typeof UsersAnalyticsRoute
  UsersListRoute: typeof UsersListRoute
  UsersNewRoute: typeof UsersNewRoute
  VendorsAnalyticsRoute: typeof VendorsAnalyticsRoute
  VendorsListRoute: typeof VendorsListRoute
  VendorsNewRoute: typeof VendorsNewRoute
  WarrantyAnalyticsRoute: typeof WarrantyAnalyticsRoute
  WarrantyListRoute: typeof WarrantyListRoute
  WarrantyNewRoute: typeof WarrantyNewRoute
  AuditsIndexRoute: typeof AuditsIndexRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  EngineerIndexRoute: typeof EngineerIndexRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  WarrantyIndexRoute: typeof WarrantyIndexRoute
  AuditsIdRespondRoute: typeof AuditsIdRespondRoute
  AuditsIdReviewRoute: typeof AuditsIdReviewRoute
  AuditsTemplatesIdRoute: typeof AuditsTemplatesIdRoute
  AuditsTemplatesNewRoute: typeof AuditsTemplatesNewRoute
  ComplaintsIdEditRoute: typeof ComplaintsIdEditRoute
  ComplaintsIdHistoryRoute: typeof ComplaintsIdHistoryRoute
  DepartmentsIdEditRoute: typeof DepartmentsIdEditRoute
  DepartmentsIdHistoryRoute: typeof DepartmentsIdHistoryRoute
  EngineerEquipmentIdRoute: typeof EngineerEquipmentIdRoute
  EquipmentIdChecklistRoute: typeof EquipmentIdChecklistRoute
  EquipmentIdEditRoute: typeof EquipmentIdEditRoute
  EquipmentIdHistoryRoute: typeof EquipmentIdHistoryRoute
  InventoryIdEditRoute: typeof InventoryIdEditRoute
  InventoryIdHistoryRoute: typeof InventoryIdHistoryRoute
  MaintenanceIdChecklistRoute: typeof MaintenanceIdChecklistRoute
  MaintenanceIdCompleteRoute: typeof MaintenanceIdCompleteRoute
  MaintenanceIdCorrectiveActionRoute: typeof MaintenanceIdCorrectiveActionRoute
  MaintenanceIdEditRoute: typeof MaintenanceIdEditRoute
  MaintenanceIdHistoryRoute: typeof MaintenanceIdHistoryRoute
  MaintenanceIdInvestigationRoute: typeof MaintenanceIdInvestigationRoute
  MaintenanceIdReportRoute: typeof MaintenanceIdReportRoute
  MaintenanceIdRootCauseRoute: typeof MaintenanceIdRootCauseRoute
  MaintenanceIdTestingRoute: typeof MaintenanceIdTestingRoute
  MaintenanceIdUploadsRoute: typeof MaintenanceIdUploadsRoute
  PurchaseOrdersIdEditRoute: typeof PurchaseOrdersIdEditRoute
  PurchaseOrdersIdHistoryRoute: typeof PurchaseOrdersIdHistoryRoute
  StaffComplaintsIdRoute: typeof StaffComplaintsIdRoute
  StaffComplaintsNewRoute: typeof StaffComplaintsNewRoute
  StaffEquipmentIdRoute: typeof StaffEquipmentIdRoute
  StaffMaintenanceIdRoute: typeof StaffMaintenanceIdRoute
  StaffReportsIdRoute: typeof StaffReportsIdRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
  UsersIdHistoryRoute: typeof UsersIdHistoryRoute
  VendorsIdEditRoute: typeof VendorsIdEditRoute
  VendorsIdHistoryRoute: typeof VendorsIdHistoryRoute
  WarrantyIdEditRoute: typeof WarrantyIdEditRoute
  WarrantyIdHistoryRoute: typeof WarrantyIdHistoryRoute
  AuditsIdIndexRoute: typeof AuditsIdIndexRoute
  AuditsTemplatesIndexRoute: typeof AuditsTemplatesIndexRoute
  ComplaintsIdIndexRoute: typeof ComplaintsIdIndexRoute
  DepartmentsIdIndexRoute: typeof DepartmentsIdIndexRoute
  EngineerTasksIndexRoute: typeof EngineerTasksIndexRoute
  EquipmentIdIndexRoute: typeof EquipmentIdIndexRoute
  InventoryIdIndexRoute: typeof InventoryIdIndexRoute
  MaintenanceIdIndexRoute: typeof MaintenanceIdIndexRoute
  PurchaseOrdersIdIndexRoute: typeof PurchaseOrdersIdIndexRoute
  StaffComplaintsIndexRoute: typeof StaffComplaintsIndexRoute
  StaffEquipmentIndexRoute: typeof StaffEquipmentIndexRoute
  StaffMaintenanceIndexRoute: typeof StaffMaintenanceIndexRoute
  StaffReportsIndexRoute: typeof StaffReportsIndexRoute
  UsersIdIndexRoute: typeof UsersIdIndexRoute
  VendorsIdIndexRoute: typeof VendorsIdIndexRoute
  WarrantyIdIndexRoute: typeof WarrantyIdIndexRoute
  EngineerTasksIdBreakdownRoute: typeof EngineerTasksIdBreakdownRoute
  EngineerTasksIdChecklistRoute: typeof EngineerTasksIdChecklistRoute
  EngineerTasksIdCompleteRoute: typeof EngineerTasksIdCompleteRoute
  EngineerTasksIdReportRoute: typeof EngineerTasksIdReportRoute
  EngineerTasksIdStartRoute: typeof EngineerTasksIdStartRoute
  EngineerTasksIdUploadsRoute: typeof EngineerTasksIdUploadsRoute
  EngineerTasksIdIndexRoute: typeof EngineerTasksIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/': {
      id: '/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/assign': {
      id: '/audits/assign'
      path: '/audits/assign'
      fullPath: '/audits/assign'
      preLoaderRoute: typeof AuditsAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/history': {
      id: '/audits/history'
      path: '/audits/history'
      fullPath: '/audits/history'
      preLoaderRoute: typeof AuditsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/analytics': {
      id: '/complaints/analytics'
      path: '/complaints/analytics'
      fullPath: '/complaints/analytics'
      preLoaderRoute: typeof ComplaintsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/list': {
      id: '/complaints/list'
      path: '/complaints/list'
      fullPath: '/complaints/list'
      preLoaderRoute: typeof ComplaintsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/new': {
      id: '/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof ComplaintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/analytics': {
      id: '/departments/analytics'
      path: '/departments/analytics'
      fullPath: '/departments/analytics'
      preLoaderRoute: typeof DepartmentsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/list': {
      id: '/departments/list'
      path: '/departments/list'
      fullPath: '/departments/list'
      preLoaderRoute: typeof DepartmentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/new': {
      id: '/departments/new'
      path: '/departments/new'
      fullPath: '/departments/new'
      preLoaderRoute: typeof DepartmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/engineer'
      fullPath: '/engineer/'
      preLoaderRoute: typeof EngineerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/calendar': {
      id: '/engineer/calendar'
      path: '/engineer/calendar'
      fullPath: '/engineer/calendar'
      preLoaderRoute: typeof EngineerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/history': {
      id: '/engineer/history'
      path: '/engineer/history'
      fullPath: '/engineer/history'
      preLoaderRoute: typeof EngineerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/performance': {
      id: '/engineer/performance'
      path: '/engineer/performance'
      fullPath: '/engineer/performance'
      preLoaderRoute: typeof EngineerPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/profile': {
      id: '/engineer/profile'
      path: '/engineer/profile'
      fullPath: '/engineer/profile'
      preLoaderRoute: typeof EngineerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/settings': {
      id: '/engineer/settings'
      path: '/engineer/settings'
      fullPath: '/engineer/settings'
      preLoaderRoute: typeof EngineerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/analytics': {
      id: '/equipment/analytics'
      path: '/equipment/analytics'
      fullPath: '/equipment/analytics'
      preLoaderRoute: typeof EquipmentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/list': {
      id: '/equipment/list'
      path: '/equipment/list'
      fullPath: '/equipment/list'
      preLoaderRoute: typeof EquipmentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/new': {
      id: '/equipment/new'
      path: '/equipment/new'
      fullPath: '/equipment/new'
      preLoaderRoute: typeof EquipmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/analytics': {
      id: '/inventory/analytics'
      path: '/inventory/analytics'
      fullPath: '/inventory/analytics'
      preLoaderRoute: typeof InventoryAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/list': {
      id: '/inventory/list'
      path: '/inventory/list'
      fullPath: '/inventory/list'
      preLoaderRoute: typeof InventoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/analytics': {
      id: '/maintenance/analytics'
      path: '/maintenance/analytics'
      fullPath: '/maintenance/analytics'
      preLoaderRoute: typeof MaintenanceAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/list': {
      id: '/maintenance/list'
      path: '/maintenance/list'
      fullPath: '/maintenance/list'
      preLoaderRoute: typeof MaintenanceListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/new': {
      id: '/maintenance/new'
      path: '/maintenance/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof MaintenanceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/analytics': {
      id: '/purchase-orders/analytics'
      path: '/purchase-orders/analytics'
      fullPath: '/purchase-orders/analytics'
      preLoaderRoute: typeof PurchaseOrdersAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/list': {
      id: '/purchase-orders/list'
      path: '/purchase-orders/list'
      fullPath: '/purchase-orders/list'
      preLoaderRoute: typeof PurchaseOrdersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/new': {
      id: '/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof PurchaseOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/department': {
      id: '/staff/department'
      path: '/staff/department'
      fullPath: '/staff/department'
      preLoaderRoute: typeof StaffDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/staff/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/staff/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/analytics': {
      id: '/users/analytics'
      path: '/users/analytics'
      fullPath: '/users/analytics'
      preLoaderRoute: typeof UsersAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/list': {
      id: '/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof UsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/analytics': {
      id: '/vendors/analytics'
      path: '/vendors/analytics'
      fullPath: '/vendors/analytics'
      preLoaderRoute: typeof VendorsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/list': {
      id: '/vendors/list'
      path: '/vendors/list'
      fullPath: '/vendors/list'
      preLoaderRoute: typeof VendorsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/new': {
      id: '/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof VendorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/': {
      id: '/warranty/'
      path: '/warranty'
      fullPath: '/warranty/'
      preLoaderRoute: typeof WarrantyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/analytics': {
      id: '/warranty/analytics'
      path: '/warranty/analytics'
      fullPath: '/warranty/analytics'
      preLoaderRoute: typeof WarrantyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/list': {
      id: '/warranty/list'
      path: '/warranty/list'
      fullPath: '/warranty/list'
      preLoaderRoute: typeof WarrantyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/new': {
      id: '/warranty/new'
      path: '/warranty/new'
      fullPath: '/warranty/new'
      preLoaderRoute: typeof WarrantyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id/': {
      id: '/audits/$id/'
      path: '/audits/$id'
      fullPath: '/audits/$id/'
      preLoaderRoute: typeof AuditsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id/respond': {
      id: '/audits/$id/respond'
      path: '/audits/$id/respond'
      fullPath: '/audits/$id/respond'
      preLoaderRoute: typeof AuditsIdRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id/review': {
      id: '/audits/$id/review'
      path: '/audits/$id/review'
      fullPath: '/audits/$id/review'
      preLoaderRoute: typeof AuditsIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/templates/': {
      id: '/audits/templates/'
      path: '/audits/templates'
      fullPath: '/audits/templates/'
      preLoaderRoute: typeof AuditsTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/templates/$id': {
      id: '/audits/templates/$id'
      path: '/audits/templates/$id'
      fullPath: '/audits/templates/$id'
      preLoaderRoute: typeof AuditsTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/templates/new': {
      id: '/audits/templates/new'
      path: '/audits/templates/new'
      fullPath: '/audits/templates/new'
      preLoaderRoute: typeof AuditsTemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id/': {
      id: '/complaints/$id/'
      path: '/complaints/$id'
      fullPath: '/complaints/$id/'
      preLoaderRoute: typeof ComplaintsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id/edit': {
      id: '/complaints/$id/edit'
      path: '/complaints/$id/edit'
      fullPath: '/complaints/$id/edit'
      preLoaderRoute: typeof ComplaintsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id/history': {
      id: '/complaints/$id/history'
      path: '/complaints/$id/history'
      fullPath: '/complaints/$id/history'
      preLoaderRoute: typeof ComplaintsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id/': {
      id: '/departments/$id/'
      path: '/departments/$id'
      fullPath: '/departments/$id/'
      preLoaderRoute: typeof DepartmentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id/edit': {
      id: '/departments/$id/edit'
      path: '/departments/$id/edit'
      fullPath: '/departments/$id/edit'
      preLoaderRoute: typeof DepartmentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id/history': {
      id: '/departments/$id/history'
      path: '/departments/$id/history'
      fullPath: '/departments/$id/history'
      preLoaderRoute: typeof DepartmentsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/equipment/$id': {
      id: '/engineer/equipment/$id'
      path: '/engineer/equipment/$id'
      fullPath: '/engineer/equipment/$id'
      preLoaderRoute: typeof EngineerEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/': {
      id: '/engineer/tasks/'
      path: '/engineer/tasks'
      fullPath: '/engineer/tasks/'
      preLoaderRoute: typeof EngineerTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id/': {
      id: '/equipment/$id/'
      path: '/equipment/$id'
      fullPath: '/equipment/$id/'
      preLoaderRoute: typeof EquipmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id/checklist': {
      id: '/equipment/$id/checklist'
      path: '/equipment/$id/checklist'
      fullPath: '/equipment/$id/checklist'
      preLoaderRoute: typeof EquipmentIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id/edit': {
      id: '/equipment/$id/edit'
      path: '/equipment/$id/edit'
      fullPath: '/equipment/$id/edit'
      preLoaderRoute: typeof EquipmentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id/history': {
      id: '/equipment/$id/history'
      path: '/equipment/$id/history'
      fullPath: '/equipment/$id/history'
      preLoaderRoute: typeof EquipmentIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id/': {
      id: '/inventory/$id/'
      path: '/inventory/$id'
      fullPath: '/inventory/$id/'
      preLoaderRoute: typeof InventoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id/edit': {
      id: '/inventory/$id/edit'
      path: '/inventory/$id/edit'
      fullPath: '/inventory/$id/edit'
      preLoaderRoute: typeof InventoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id/history': {
      id: '/inventory/$id/history'
      path: '/inventory/$id/history'
      fullPath: '/inventory/$id/history'
      preLoaderRoute: typeof InventoryIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/': {
      id: '/maintenance/$id/'
      path: '/maintenance/$id'
      fullPath: '/maintenance/$id/'
      preLoaderRoute: typeof MaintenanceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/checklist': {
      id: '/maintenance/$id/checklist'
      path: '/maintenance/$id/checklist'
      fullPath: '/maintenance/$id/checklist'
      preLoaderRoute: typeof MaintenanceIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/complete': {
      id: '/maintenance/$id/complete'
      path: '/maintenance/$id/complete'
      fullPath: '/maintenance/$id/complete'
      preLoaderRoute: typeof MaintenanceIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/corrective-action': {
      id: '/maintenance/$id/corrective-action'
      path: '/maintenance/$id/corrective-action'
      fullPath: '/maintenance/$id/corrective-action'
      preLoaderRoute: typeof MaintenanceIdCorrectiveActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/edit': {
      id: '/maintenance/$id/edit'
      path: '/maintenance/$id/edit'
      fullPath: '/maintenance/$id/edit'
      preLoaderRoute: typeof MaintenanceIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/history': {
      id: '/maintenance/$id/history'
      path: '/maintenance/$id/history'
      fullPath: '/maintenance/$id/history'
      preLoaderRoute: typeof MaintenanceIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/investigation': {
      id: '/maintenance/$id/investigation'
      path: '/maintenance/$id/investigation'
      fullPath: '/maintenance/$id/investigation'
      preLoaderRoute: typeof MaintenanceIdInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/report': {
      id: '/maintenance/$id/report'
      path: '/maintenance/$id/report'
      fullPath: '/maintenance/$id/report'
      preLoaderRoute: typeof MaintenanceIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/root-cause': {
      id: '/maintenance/$id/root-cause'
      path: '/maintenance/$id/root-cause'
      fullPath: '/maintenance/$id/root-cause'
      preLoaderRoute: typeof MaintenanceIdRootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/testing': {
      id: '/maintenance/$id/testing'
      path: '/maintenance/$id/testing'
      fullPath: '/maintenance/$id/testing'
      preLoaderRoute: typeof MaintenanceIdTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/$id/uploads': {
      id: '/maintenance/$id/uploads'
      path: '/maintenance/$id/uploads'
      fullPath: '/maintenance/$id/uploads'
      preLoaderRoute: typeof MaintenanceIdUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$id/': {
      id: '/purchase-orders/$id/'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id/'
      preLoaderRoute: typeof PurchaseOrdersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$id/edit': {
      id: '/purchase-orders/$id/edit'
      path: '/purchase-orders/$id/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof PurchaseOrdersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$id/history': {
      id: '/purchase-orders/$id/history'
      path: '/purchase-orders/$id/history'
      fullPath: '/purchase-orders/$id/history'
      preLoaderRoute: typeof PurchaseOrdersIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/complaints/': {
      id: '/staff/complaints/'
      path: '/staff/complaints'
      fullPath: '/staff/complaints/'
      preLoaderRoute: typeof StaffComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/complaints/$id': {
      id: '/staff/complaints/$id'
      path: '/staff/complaints/$id'
      fullPath: '/staff/complaints/$id'
      preLoaderRoute: typeof StaffComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/complaints/new': {
      id: '/staff/complaints/new'
      path: '/staff/complaints/new'
      fullPath: '/staff/complaints/new'
      preLoaderRoute: typeof StaffComplaintsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/equipment/': {
      id: '/staff/equipment/'
      path: '/staff/equipment'
      fullPath: '/staff/equipment/'
      preLoaderRoute: typeof StaffEquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/equipment/$id': {
      id: '/staff/equipment/$id'
      path: '/staff/equipment/$id'
      fullPath: '/staff/equipment/$id'
      preLoaderRoute: typeof StaffEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/maintenance/': {
      id: '/staff/maintenance/'
      path: '/staff/maintenance'
      fullPath: '/staff/maintenance/'
      preLoaderRoute: typeof StaffMaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/maintenance/$id': {
      id: '/staff/maintenance/$id'
      path: '/staff/maintenance/$id'
      fullPath: '/staff/maintenance/$id'
      preLoaderRoute: typeof StaffMaintenanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports/': {
      id: '/staff/reports/'
      path: '/staff/reports'
      fullPath: '/staff/reports/'
      preLoaderRoute: typeof StaffReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports/$id': {
      id: '/staff/reports/$id'
      path: '/staff/reports/$id'
      fullPath: '/staff/reports/$id'
      preLoaderRoute: typeof StaffReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/': {
      id: '/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof UsersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/history': {
      id: '/users/$id/history'
      path: '/users/$id/history'
      fullPath: '/users/$id/history'
      preLoaderRoute: typeof UsersIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id/': {
      id: '/vendors/$id/'
      path: '/vendors/$id'
      fullPath: '/vendors/$id/'
      preLoaderRoute: typeof VendorsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id/edit': {
      id: '/vendors/$id/edit'
      path: '/vendors/$id/edit'
      fullPath: '/vendors/$id/edit'
      preLoaderRoute: typeof VendorsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id/history': {
      id: '/vendors/$id/history'
      path: '/vendors/$id/history'
      fullPath: '/vendors/$id/history'
      preLoaderRoute: typeof VendorsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/$id/': {
      id: '/warranty/$id/'
      path: '/warranty/$id'
      fullPath: '/warranty/$id/'
      preLoaderRoute: typeof WarrantyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/$id/edit': {
      id: '/warranty/$id/edit'
      path: '/warranty/$id/edit'
      fullPath: '/warranty/$id/edit'
      preLoaderRoute: typeof WarrantyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty/$id/history': {
      id: '/warranty/$id/history'
      path: '/warranty/$id/history'
      fullPath: '/warranty/$id/history'
      preLoaderRoute: typeof WarrantyIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/': {
      id: '/engineer/tasks/$id/'
      path: '/engineer/tasks/$id'
      fullPath: '/engineer/tasks/$id/'
      preLoaderRoute: typeof EngineerTasksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/breakdown': {
      id: '/engineer/tasks/$id/breakdown'
      path: '/engineer/tasks/$id/breakdown'
      fullPath: '/engineer/tasks/$id/breakdown'
      preLoaderRoute: typeof EngineerTasksIdBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/checklist': {
      id: '/engineer/tasks/$id/checklist'
      path: '/engineer/tasks/$id/checklist'
      fullPath: '/engineer/tasks/$id/checklist'
      preLoaderRoute: typeof EngineerTasksIdChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/complete': {
      id: '/engineer/tasks/$id/complete'
      path: '/engineer/tasks/$id/complete'
      fullPath: '/engineer/tasks/$id/complete'
      preLoaderRoute: typeof EngineerTasksIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/report': {
      id: '/engineer/tasks/$id/report'
      path: '/engineer/tasks/$id/report'
      fullPath: '/engineer/tasks/$id/report'
      preLoaderRoute: typeof EngineerTasksIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/start': {
      id: '/engineer/tasks/$id/start'
      path: '/engineer/tasks/$id/start'
      fullPath: '/engineer/tasks/$id/start'
      preLoaderRoute: typeof EngineerTasksIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/tasks/$id/uploads': {
      id: '/engineer/tasks/$id/uploads'
      path: '/engineer/tasks/$id/uploads'
      fullPath: '/engineer/tasks/$id/uploads'
      preLoaderRoute: typeof EngineerTasksIdUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  AuditsAssignRoute: AuditsAssignRoute,
  AuditsHistoryRoute: AuditsHistoryRoute,
  ComplaintsAnalyticsRoute: ComplaintsAnalyticsRoute,
  ComplaintsListRoute: ComplaintsListRoute,
  ComplaintsNewRoute: ComplaintsNewRoute,
  DepartmentsAnalyticsRoute: DepartmentsAnalyticsRoute,
  DepartmentsListRoute: DepartmentsListRoute,
  DepartmentsNewRoute: DepartmentsNewRoute,
  EngineerCalendarRoute: EngineerCalendarRoute,
  EngineerHistoryRoute: EngineerHistoryRoute,
  EngineerPerformanceRoute: EngineerPerformanceRoute,
  EngineerProfileRoute: EngineerProfileRoute,
  EngineerSettingsRoute: EngineerSettingsRoute,
  EquipmentAnalyticsRoute: EquipmentAnalyticsRoute,
  EquipmentListRoute: EquipmentListRoute,
  EquipmentNewRoute: EquipmentNewRoute,
  InventoryAnalyticsRoute: InventoryAnalyticsRoute,
  InventoryListRoute: InventoryListRoute,
  InventoryNewRoute: InventoryNewRoute,
  MaintenanceAnalyticsRoute: MaintenanceAnalyticsRoute,
  MaintenanceListRoute: MaintenanceListRoute,
  MaintenanceNewRoute: MaintenanceNewRoute,
  PurchaseOrdersAnalyticsRoute: PurchaseOrdersAnalyticsRoute,
  PurchaseOrdersListRoute: PurchaseOrdersListRoute,
  PurchaseOrdersNewRoute: PurchaseOrdersNewRoute,
  StaffDepartmentRoute: StaffDepartmentRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  UsersAnalyticsRoute: UsersAnalyticsRoute,
  UsersListRoute: UsersListRoute,
  UsersNewRoute: UsersNewRoute,
  VendorsAnalyticsRoute: VendorsAnalyticsRoute,
  VendorsListRoute: VendorsListRoute,
  VendorsNewRoute: VendorsNewRoute,
  WarrantyAnalyticsRoute: WarrantyAnalyticsRoute,
  WarrantyListRoute: WarrantyListRoute,
  WarrantyNewRoute: WarrantyNewRoute,
  AuditsIndexRoute: AuditsIndexRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  EngineerIndexRoute: EngineerIndexRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  WarrantyIndexRoute: WarrantyIndexRoute,
  AuditsIdRespondRoute: AuditsIdRespondRoute,
  AuditsIdReviewRoute: AuditsIdReviewRoute,
  AuditsTemplatesIdRoute: AuditsTemplatesIdRoute,
  AuditsTemplatesNewRoute: AuditsTemplatesNewRoute,
  ComplaintsIdEditRoute: ComplaintsIdEditRoute,
  ComplaintsIdHistoryRoute: ComplaintsIdHistoryRoute,
  DepartmentsIdEditRoute: DepartmentsIdEditRoute,
  DepartmentsIdHistoryRoute: DepartmentsIdHistoryRoute,
  EngineerEquipmentIdRoute: EngineerEquipmentIdRoute,
  EquipmentIdChecklistRoute: EquipmentIdChecklistRoute,
  EquipmentIdEditRoute: EquipmentIdEditRoute,
  EquipmentIdHistoryRoute: EquipmentIdHistoryRoute,
  InventoryIdEditRoute: InventoryIdEditRoute,
  InventoryIdHistoryRoute: InventoryIdHistoryRoute,
  MaintenanceIdChecklistRoute: MaintenanceIdChecklistRoute,
  MaintenanceIdCompleteRoute: MaintenanceIdCompleteRoute,
  MaintenanceIdCorrectiveActionRoute: MaintenanceIdCorrectiveActionRoute,
  MaintenanceIdEditRoute: MaintenanceIdEditRoute,
  MaintenanceIdHistoryRoute: MaintenanceIdHistoryRoute,
  MaintenanceIdInvestigationRoute: MaintenanceIdInvestigationRoute,
  MaintenanceIdReportRoute: MaintenanceIdReportRoute,
  MaintenanceIdRootCauseRoute: MaintenanceIdRootCauseRoute,
  MaintenanceIdTestingRoute: MaintenanceIdTestingRoute,
  MaintenanceIdUploadsRoute: MaintenanceIdUploadsRoute,
  PurchaseOrdersIdEditRoute: PurchaseOrdersIdEditRoute,
  PurchaseOrdersIdHistoryRoute: PurchaseOrdersIdHistoryRoute,
  StaffComplaintsIdRoute: StaffComplaintsIdRoute,
  StaffComplaintsNewRoute: StaffComplaintsNewRoute,
  StaffEquipmentIdRoute: StaffEquipmentIdRoute,
  StaffMaintenanceIdRoute: StaffMaintenanceIdRoute,
  StaffReportsIdRoute: StaffReportsIdRoute,
  UsersIdEditRoute: UsersIdEditRoute,
  UsersIdHistoryRoute: UsersIdHistoryRoute,
  VendorsIdEditRoute: VendorsIdEditRoute,
  VendorsIdHistoryRoute: VendorsIdHistoryRoute,
  WarrantyIdEditRoute: WarrantyIdEditRoute,
  WarrantyIdHistoryRoute: WarrantyIdHistoryRoute,
  AuditsIdIndexRoute: AuditsIdIndexRoute,
  AuditsTemplatesIndexRoute: AuditsTemplatesIndexRoute,
  ComplaintsIdIndexRoute: ComplaintsIdIndexRoute,
  DepartmentsIdIndexRoute: DepartmentsIdIndexRoute,
  EngineerTasksIndexRoute: EngineerTasksIndexRoute,
  EquipmentIdIndexRoute: EquipmentIdIndexRoute,
  InventoryIdIndexRoute: InventoryIdIndexRoute,
  MaintenanceIdIndexRoute: MaintenanceIdIndexRoute,
  PurchaseOrdersIdIndexRoute: PurchaseOrdersIdIndexRoute,
  StaffComplaintsIndexRoute: StaffComplaintsIndexRoute,
  StaffEquipmentIndexRoute: StaffEquipmentIndexRoute,
  StaffMaintenanceIndexRoute: StaffMaintenanceIndexRoute,
  StaffReportsIndexRoute: StaffReportsIndexRoute,
  UsersIdIndexRoute: UsersIdIndexRoute,
  VendorsIdIndexRoute: VendorsIdIndexRoute,
  WarrantyIdIndexRoute: WarrantyIdIndexRoute,
  EngineerTasksIdBreakdownRoute: EngineerTasksIdBreakdownRoute,
  EngineerTasksIdChecklistRoute: EngineerTasksIdChecklistRoute,
  EngineerTasksIdCompleteRoute: EngineerTasksIdCompleteRoute,
  EngineerTasksIdReportRoute: EngineerTasksIdReportRoute,
  EngineerTasksIdStartRoute: EngineerTasksIdStartRoute,
  EngineerTasksIdUploadsRoute: EngineerTasksIdUploadsRoute,
  EngineerTasksIdIndexRoute: EngineerTasksIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
