export type Status = "operational" | "maintenance" | "critical" | "idle";

export const kpis = [
  { key: "assets", label: "Total Assets", value: "2,486", delta: "+4.2%", trend: "up" as const },
  { key: "uptime", label: "Fleet Uptime", value: "98.4%", delta: "+0.8%", trend: "up" as const },
  { key: "open", label: "Open Complaints", value: "37", delta: "-12%", trend: "down" as const },
  { key: "cost", label: "Monthly Spend", value: "$184.2K", delta: "-6.1%", trend: "down" as const },
];

export const healthTrend = [
  { month: "Jan", health: 92, uptime: 95, incidents: 24 },
  { month: "Feb", health: 93, uptime: 94, incidents: 21 },
  { month: "Mar", health: 91, uptime: 96, incidents: 27 },
  { month: "Apr", health: 94, uptime: 97, incidents: 18 },
  { month: "May", health: 96, uptime: 97, incidents: 14 },
  { month: "Jun", health: 95, uptime: 98, incidents: 16 },
  { month: "Jul", health: 97, uptime: 98, incidents: 11 },
  { month: "Aug", health: 98, uptime: 99, incidents: 9 },
];

export const departments = [
  { name: "Radiology", assets: 412, uptime: 98.9, complaints: 6, staff: 48, score: 94, spend: 42 },
  { name: "ICU", assets: 336, uptime: 99.4, complaints: 3, staff: 61, score: 97, spend: 38 },
  {
    name: "Operating Theatre",
    assets: 288,
    uptime: 97.2,
    complaints: 9,
    staff: 54,
    score: 88,
    spend: 35,
  },
  { name: "Emergency", assets: 254, uptime: 96.1, complaints: 11, staff: 72, score: 84, spend: 29 },
  { name: "Laboratory", assets: 361, uptime: 98.1, complaints: 5, staff: 39, score: 91, spend: 24 },
  { name: "Cardiology", assets: 219, uptime: 98.7, complaints: 3, staff: 33, score: 93, spend: 21 },
];

export const engineers = [
  {
    name: "Anita Raghavan",
    role: "Biomedical Lead",
    load: 82,
    open: 7,
    avatar: "AR",
    zone: "Radiology",
  },
  { name: "Daniel Okafor", role: "Senior Engineer", load: 64, open: 5, avatar: "DO", zone: "ICU" },
  {
    name: "Mei Lin Chan",
    role: "Field Engineer",
    load: 45,
    open: 3,
    avatar: "MC",
    zone: "Laboratory",
  },
  {
    name: "Tomás Herrera",
    role: "Field Engineer",
    load: 91,
    open: 9,
    avatar: "TH",
    zone: "Emergency",
  },
  {
    name: "Priya Nair",
    role: "Calibration Specialist",
    load: 38,
    open: 2,
    avatar: "PN",
    zone: "Cardiology",
  },
];

export type EquipmentSpecs = {
  model: string;
  serial: string;
  manufactured: string;
  installed: string;
  location: string;
  owner: string;
  power: string;
  weight: string;
  dimensions: string;
  software: string;
  riskClass: string;
  usageHours: string;
  lastService: string;
  nextService: string;
  amc: string;
  compliance: string;
};

export const equipment = [
  {
    id: "EQ-1042",
    name: "Siemens MAGNETOM Vida 3T",
    category: "Imaging",
    dept: "Radiology",
    status: "operational" as Status,
    health: 96,
    warranty: "14 Mar 2027",
    vendor: "Siemens Healthineers",
    cost: "$1.84M",
    specs: {
      model: "MAGNETOM Vida 3T",
      serial: "SN-VIDA-104229",
      manufactured: "Nov 2023",
      installed: "12 Feb 2024",
      location: "Radiology · Level 2 · Scan Room A",
      owner: "Dr. L. Fontaine",
      power: "380 V · 45 kVA · 3-phase",
      weight: "6,200 kg",
      dimensions: "2.55 × 2.10 × 1.98 m",
      software: "syngo MR XA50 (v4.2)",
      riskClass: "Class IIb",
      usageHours: "4,318 h",
      lastService: "22 Nov 2025",
      nextService: "18 Sep 2026",
      amc: "Comprehensive · $42.6K / yr",
      compliance: "IEC 60601-1 · CE · FDA 510(k)",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-2210",
    name: "GE CARESCAPE R860 Ventilator",
    category: "Life Support",
    dept: "ICU",
    status: "maintenance" as Status,
    health: 78,
    warranty: "02 Sep 2026",
    vendor: "GE Healthcare",
    cost: "$46K",
    specs: {
      model: "CARESCAPE R860",
      serial: "SN-R860-221074",
      manufactured: "Mar 2023",
      installed: "04 Jul 2023",
      location: "ICU · Level 4 · Bay 6",
      owner: "Dr. M. Adeyemi",
      power: "230 V · 400 VA",
      weight: "62 kg",
      dimensions: "0.61 × 0.58 × 1.40 m",
      software: "R860 v11.2",
      riskClass: "Class IIb",
      usageHours: "9,842 h",
      lastService: "14 Apr 2026",
      nextService: "20 Aug 2026",
      amc: "Comprehensive · $6.2K / yr",
      compliance: "IEC 60601-1 · ISO 80601-2-12",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-3381",
    name: "Philips Azurion 7 Cath Lab",
    category: "Imaging",
    dept: "Cardiology",
    status: "operational" as Status,
    health: 92,
    warranty: "27 Jan 2028",
    vendor: "Philips",
    cost: "$1.12M",
    specs: {
      model: "Azurion 7 B20/15",
      serial: "SN-AZ7-338115",
      manufactured: "Aug 2024",
      installed: "27 Jan 2025",
      location: "Cardiology · Level 3 · Cath Lab 2",
      owner: "Dr. R. Bhattacharya",
      power: "400 V · 80 kVA · 3-phase",
      weight: "1,980 kg",
      dimensions: "5.20 × 4.10 × 2.90 m",
      software: "Azurion R2.1",
      riskClass: "Class IIb",
      usageHours: "2,106 h",
      lastService: "09 Mar 2026",
      nextService: "09 Sep 2026",
      amc: "Comprehensive · $28.4K / yr",
      compliance: "IEC 60601-1 · CE · FDA 510(k)",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-4127",
    name: "Dräger Perseus A500 Anesthesia",
    category: "Surgical",
    dept: "Operating Theatre",
    status: "critical" as Status,
    health: 51,
    warranty: "18 Jun 2026",
    vendor: "Dräger",
    cost: "$78K",
    specs: {
      model: "Perseus A500",
      serial: "SN-PA500-412703",
      manufactured: "Jan 2022",
      installed: "18 Jun 2022",
      location: "Operating Theatre · Level 5 · OT 3",
      owner: "Dr. K. Sørensen",
      power: "230 V · 900 VA",
      weight: "148 kg",
      dimensions: "1.28 × 0.80 × 1.55 m",
      software: "Perseus SW 2.05",
      riskClass: "Class IIb",
      usageHours: "12,540 h",
      lastService: "02 Feb 2026",
      nextService: "Overdue · 12 Jul 2026",
      amc: "Basic · $8.9K / yr",
      compliance: "IEC 60601-1 · ISO 80601-2-13",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-5563",
    name: "Roche cobas 8000 Analyzer",
    category: "Diagnostics",
    dept: "Laboratory",
    status: "operational" as Status,
    health: 89,
    warranty: "09 Nov 2027",
    vendor: "Roche",
    cost: "$310K",
    specs: {
      model: "cobas 8000 modular <c702>",
      serial: "SN-C8000-556341",
      manufactured: "May 2024",
      installed: "09 Nov 2024",
      location: "Laboratory · Level 1 · Core Lab",
      owner: "Dr. P. Nair",
      power: "400 V · 12 kVA",
      weight: "1,120 kg",
      dimensions: "4.40 × 1.05 × 1.60 m",
      software: "cobas IT 3000 v1.9",
      riskClass: "Class IIa",
      usageHours: "6,275 h",
      lastService: "30 May 2026",
      nextService: "30 Nov 2026",
      amc: "Comprehensive · $19.8K / yr",
      compliance: "IVDR · CE · ISO 15189",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-6612",
    name: "Mindray BeneVision N22 Monitor",
    category: "Monitoring",
    dept: "Emergency",
    status: "idle" as Status,
    health: 84,
    warranty: "21 Apr 2026",
    vendor: "Mindray",
    cost: "$18K",
    specs: {
      model: "BeneVision N22",
      serial: "SN-N22-661288",
      manufactured: "Feb 2023",
      installed: "21 Apr 2023",
      location: "Emergency · Level 0 · Resus Bay 2",
      owner: "Dr. T. Herrera",
      power: "230 V · 180 VA",
      weight: "11 kg",
      dimensions: "0.52 × 0.19 × 0.42 m",
      software: "BeneVision v3.14",
      riskClass: "Class IIa",
      usageHours: "8,910 h",
      lastService: "11 Jan 2026",
      nextService: "11 Oct 2026",
      amc: "Basic · $2.1K / yr",
      compliance: "IEC 60601-1 · IEC 60601-2-49",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-7745",
    name: "Stryker System 9 Surgical Drill",
    category: "Surgical",
    dept: "Operating Theatre",
    status: "operational" as Status,
    health: 94,
    warranty: "30 Dec 2026",
    vendor: "Stryker",
    cost: "$32K",
    specs: {
      model: "System 9 Rotary Handpiece",
      serial: "SN-SYS9-774560",
      manufactured: "Sep 2023",
      installed: "30 Dec 2023",
      location: "Operating Theatre · Level 5 · Sterile Store",
      owner: "N. Farrell (Scrub Lead)",
      power: "Battery · 14.4 V Li-ion",
      weight: "1.4 kg",
      dimensions: "0.21 × 0.06 × 0.14 m",
      software: "Firmware 5.3",
      riskClass: "Class IIa",
      usageHours: "1,180 h",
      lastService: "18 Jun 2026",
      nextService: "18 Dec 2026",
      amc: "Comprehensive · $3.4K / yr",
      compliance: "IEC 60601-1 · ISO 13485",
    } as EquipmentSpecs,
  },
  {
    id: "EQ-8890",
    name: "Baxter Prismaflex Dialysis",
    category: "Life Support",
    dept: "ICU",
    status: "maintenance" as Status,
    health: 73,
    warranty: "12 Aug 2026",
    vendor: "Baxter",
    cost: "$54K",
    specs: {
      model: "Prismaflex System 8.0",
      serial: "SN-PFX-889012",
      manufactured: "Jun 2022",
      installed: "12 Aug 2022",
      location: "ICU · Level 4 · Renal Bay",
      owner: "Dr. M. Adeyemi",
      power: "230 V · 500 VA",
      weight: "96 kg",
      dimensions: "0.66 × 0.60 × 1.62 m",
      software: "Prismaflex SW 8.10",
      riskClass: "Class IIb",
      usageHours: "10,430 h",
      lastService: "27 Mar 2026",
      nextService: "05 Sep 2026",
      amc: "Comprehensive · $7.6K / yr",
      compliance: "IEC 60601-1 · ISO 80601-2-16",
    } as EquipmentSpecs,
  },
];

export const categories = [
  { name: "Imaging", count: 486, health: 94, color: "var(--chart-1)" },
  { name: "Life Support", count: 372, health: 88, color: "var(--chart-2)" },
  { name: "Surgical", count: 298, health: 91, color: "var(--chart-3)" },
  { name: "Diagnostics", count: 544, health: 96, color: "var(--chart-4)" },
  { name: "Monitoring", count: 786, health: 92, color: "var(--chart-5)" },
];

export const complaints = [
  {
    id: "CMP-8842",
    title: "MRI coil overheating during long scans",
    equipment: "Siemens MAGNETOM Vida 3T",
    dept: "Radiology",
    priority: "Critical",
    status: "In Progress",
    age: "4h",
    assignee: "Anita Raghavan",
    sla: 62,
  },
  {
    id: "CMP-8836",
    title: "Ventilator humidifier alarm intermittently firing",
    equipment: "GE CARESCAPE R860",
    dept: "ICU",
    priority: "High",
    status: "Triage",
    age: "9h",
    assignee: "Daniel Okafor",
    sla: 38,
  },
  {
    id: "CMP-8829",
    title: "Anesthesia machine gas calibration drift",
    equipment: "Dräger Perseus A500",
    dept: "Operating Theatre",
    priority: "Critical",
    status: "Escalated",
    age: "1d",
    assignee: "Tomás Herrera",
    sla: 88,
  },
  {
    id: "CMP-8814",
    title: "Analyzer sample probe misalignment",
    equipment: "Roche cobas 8000",
    dept: "Laboratory",
    priority: "Medium",
    status: "In Progress",
    age: "1d",
    assignee: "Mei Lin Chan",
    sla: 24,
  },
  {
    id: "CMP-8801",
    title: "Patient monitor touchscreen unresponsive",
    equipment: "Mindray BeneVision N22",
    dept: "Emergency",
    priority: "Low",
    status: "Resolved",
    age: "2d",
    assignee: "Priya Nair",
    sla: 12,
  },
  {
    id: "CMP-8797",
    title: "Cath lab detector image noise",
    equipment: "Philips Azurion 7",
    dept: "Cardiology",
    priority: "High",
    status: "In Progress",
    age: "2d",
    assignee: "Anita Raghavan",
    sla: 51,
  },
];

export const maintenance = [
  {
    id: "WO-4471",
    task: "Quarterly preventive service",
    equipment: "Siemens MAGNETOM Vida 3T",
    time: "08:30",
    dept: "Radiology",
    engineer: "Anita Raghavan",
    progress: 100,
    type: "Preventive",
  },
  {
    id: "WO-4472",
    task: "Ventilator flow sensor replacement",
    equipment: "GE CARESCAPE R860",
    time: "10:15",
    dept: "ICU",
    engineer: "Daniel Okafor",
    progress: 65,
    type: "Corrective",
  },
  {
    id: "WO-4473",
    task: "Anesthesia gas calibration",
    equipment: "Dräger Perseus A500",
    time: "12:00",
    dept: "Operating Theatre",
    engineer: "Tomás Herrera",
    progress: 30,
    type: "Calibration",
  },
  {
    id: "WO-4474",
    task: "Analyzer probe alignment",
    equipment: "Roche cobas 8000",
    time: "14:45",
    dept: "Laboratory",
    engineer: "Mei Lin Chan",
    progress: 0,
    type: "Corrective",
  },
  {
    id: "WO-4475",
    task: "Battery load test",
    equipment: "Mindray BeneVision N22",
    time: "16:30",
    dept: "Emergency",
    engineer: "Priya Nair",
    progress: 0,
    type: "Preventive",
  },
];

export const warranties = [
  {
    id: "AMC-2291",
    vendor: "Siemens Healthineers",
    assets: 186,
    type: "Comprehensive AMC",
    expires: "14 Mar 2027",
    days: 214,
    value: "$412K",
    coverage: 96,
  },
  {
    id: "AMC-2288",
    vendor: "GE Healthcare",
    assets: 142,
    type: "Warranty",
    expires: "02 Sep 2026",
    days: 30,
    value: "$268K",
    coverage: 74,
  },
  {
    id: "AMC-2274",
    vendor: "Philips",
    assets: 118,
    type: "Comprehensive AMC",
    expires: "27 Jan 2028",
    days: 540,
    value: "$355K",
    coverage: 91,
  },
  {
    id: "AMC-2262",
    vendor: "Dräger",
    assets: 64,
    type: "Non-comprehensive",
    expires: "18 Jun 2026",
    days: 12,
    value: "$96K",
    coverage: 48,
  },
  {
    id: "AMC-2250",
    vendor: "Roche",
    assets: 97,
    type: "Comprehensive AMC",
    expires: "09 Nov 2027",
    days: 460,
    value: "$204K",
    coverage: 88,
  },
];

export const users = [
  {
    name: "Emilia Greene",
    handle: "@emilia.greene",
    role: "Administrator",
    dept: "Operations",
    status: "Active",
    last: "2 min ago",
    actions: 1284,
    avatar: "EG",
  },
  {
    name: "Anita Raghavan",
    handle: "@anita.r",
    role: "Biomedical Lead",
    dept: "Radiology",
    status: "Active",
    last: "12 min ago",
    actions: 942,
    avatar: "AR",
  },
  {
    name: "Daniel Okafor",
    handle: "@d.okafor",
    role: "Engineer",
    dept: "ICU",
    status: "Active",
    last: "38 min ago",
    actions: 761,
    avatar: "DO",
  },
  {
    name: "Mei Lin Chan",
    handle: "@meilin",
    role: "Engineer",
    dept: "Laboratory",
    status: "Away",
    last: "3 h ago",
    actions: 508,
    avatar: "MC",
  },
  {
    name: "Tomás Herrera",
    handle: "@t.herrera",
    role: "Engineer",
    dept: "Emergency",
    status: "Active",
    last: "1 h ago",
    actions: 654,
    avatar: "TH",
  },
  {
    name: "Priya Nair",
    handle: "@priya.nair",
    role: "Specialist",
    dept: "Cardiology",
    status: "Offline",
    last: "2 d ago",
    actions: 331,
    avatar: "PN",
  },
  {
    name: "Jonas Weber",
    handle: "@j.weber",
    role: "Auditor",
    dept: "Compliance",
    status: "Active",
    last: "22 min ago",
    actions: 189,
    avatar: "JW",
  },
  {
    name: "Sara Aldrin",
    handle: "@s.aldrin",
    role: "Procurement",
    dept: "Finance",
    status: "Away",
    last: "5 h ago",
    actions: 275,
    avatar: "SA",
  },
];

export const activities = [
  {
    who: "Anita Raghavan",
    what: "closed complaint CMP-8790 on MAGNETOM Vida",
    when: "6 min ago",
    tone: "success",
  },
  {
    who: "System",
    what: "flagged Dräger Perseus A500 as critical health",
    when: "24 min ago",
    tone: "danger",
  },
  {
    who: "Daniel Okafor",
    what: "started work order WO-4472 in ICU",
    when: "51 min ago",
    tone: "info",
  },
  {
    who: "Sara Aldrin",
    what: "renewed AMC-2250 with Roche for 24 months",
    when: "2 h ago",
    tone: "violet",
  },
  {
    who: "Mei Lin Chan",
    what: "uploaded calibration report for cobas 8000",
    when: "3 h ago",
    tone: "info",
  },
  {
    who: "Jonas Weber",
    what: "exported Q3 compliance audit package",
    when: "5 h ago",
    tone: "warning",
  },
];

export const notifications = [
  {
    title: "Dräger Perseus A500 health dropped to 51%",
    meta: "Operating Theatre · 12 min ago",
    tone: "danger",
  },
  { title: "AMC-2262 expires in 12 days", meta: "Contracts · 1 h ago", tone: "warning" },
  {
    title: "18 preventive tasks scheduled for tomorrow",
    meta: "Maintenance · 2 h ago",
    tone: "info",
  },
  { title: "Radiology uptime crossed 99% this week", meta: "Analytics · 4 h ago", tone: "success" },
];

export const schedule = [
  { time: "08:30", title: "MRI quarterly service", where: "Radiology · Suite 2", tone: "success" },
  { time: "10:15", title: "Ventilator sensor swap", where: "ICU · Bay 4", tone: "info" },
  { time: "12:00", title: "Gas calibration", where: "OT · Theatre 1", tone: "warning" },
  { time: "15:00", title: "Vendor review — Philips", where: "Boardroom", tone: "violet" },
  { time: "17:30", title: "Shift handover briefing", where: "Biomedical Wing", tone: "info" },
];

export const costSplit = [
  { name: "Preventive", value: 42 },
  { name: "Corrective", value: 27 },
  { name: "Spare parts", value: 18 },
  { name: "Vendor AMC", value: 13 },
];

export const complaintFlow = [
  { day: "Mon", raised: 14, resolved: 11 },
  { day: "Tue", raised: 18, resolved: 16 },
  { day: "Wed", raised: 11, resolved: 14 },
  { day: "Thu", raised: 21, resolved: 17 },
  { day: "Fri", raised: 16, resolved: 19 },
  { day: "Sat", raised: 8, resolved: 9 },
  { day: "Sun", raised: 6, resolved: 7 },
];

export const radarData = [
  { axis: "Uptime", A: 96 },
  { axis: "Response", A: 88 },
  { axis: "Compliance", A: 93 },
  { axis: "Cost", A: 79 },
  { axis: "Training", A: 84 },
  { axis: "Safety", A: 97 },
];

export const statusTone: Record<Status, { label: string; cls: string }> = {
  operational: { label: "Operational", cls: "bg-success-soft text-success" },
  maintenance: { label: "In Service", cls: "bg-warning-soft text-warning" },
  critical: { label: "Critical", cls: "bg-danger-soft text-danger" },
  idle: { label: "Idle", cls: "bg-muted text-muted-foreground" },
};
